#!/usr/bin/env bash

mkdir -p ~/Annotation/Data

cd ~/Annotation/Data

wget -N ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz
gzip -fd Pfam-A.hmm.gz

wget -N ftp://ftp.expasy.org/databases/enzyme/enzyme.dat

wget -N ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz
gzip -fd uniprot_sprot.fasta.gz
